apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: nexus
      group: cicd
      template: cicd
    name: sonartype-nexus-base
  spec:
    tags:
    - annotations:
        description: The SonarType's Base Nexus Docker image
      from:
        kind: DockerImage
        name: sonatype/nexus3:latest
      importPolicy: {}
      name: "latest"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: nexus
      group: cicd
      template: cicd
    name: nexus
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: nexus:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: nexus
      git:
        ref: master
        uri: https://github.com/domenicbove/nexus-openshift-demo
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: sonartype-nexus-base:latest
      type: Docker
    triggers:
    - github:
        secret: 1802aa5420b11b2c
      type: GitHub
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: nexus
      group: cicd
      template: cicd
    name: nexus
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Sonatype Nexus repository manager's http port
    labels:
      app: nexus
      group: cicd
      template: cicd
    name: nexus
  spec:
    ports:
    - name: web
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: nexus
      deploymentconfig: nexus
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: nexus
      group: cicd
      template: cicd
    name: nexus
  spec:
    port:
      targetPort: web
    to:
      kind: Service
      name: nexus
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: nexus
      group: cicd
      template: cicd
    name: nexus
  spec:
    replicas: 1
    selector:
      app: nexus
      deploymentconfig: nexus
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: nexus
          deploymentconfig: nexus
      spec:
        containers:
        - image: ' '
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /content/groups/public
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: nexus
          ports:
          - containerPort: 8081
            protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /content/groups/public
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/nexus-work
            name: nexus-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: nexus-data
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nexus
        from:
          kind: ImageStreamTag
          name: nexus:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
